<a href="https://colab.research.google.com/github/ohki-yu0225/toukei_1B_1/blob/main/261002_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 母集団と標本
母集団：統計調査の対象となるデータ全体の集合 <br>
標本：実際に調査対象となる母集団の一部（部分集合データ） <br>
標本抽出：母集団から標本を取り出すこと <br>

今回の実習では，サンプルデータを母集団として，いくつかの条件で標本を抽出する練習をする。実際は，標本抽出されたデータがデータ分析の対象となるので，母集団のデータから標本を抽出するということはなく，母集団のデータがない状態となる適切な標本抽出の方法を検討する必要がある。

### 母集団から標本を抽出する
ある学校には普通科，理数科，国際科の3つのコースがあり，それぞれ20人ずつが所属している。このクラスの国語，数学，英語のテストの点数，身長，所属している科を記録したデータを用いて，標本を抽出のプロセスを練習する。

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame([
    [67, 88, 72, 164.2, '理数'],
    [69, 97, 62, 170.8, '理数'],
    [70, 84, 72, 143.9, '理数'],
    [70, 65, 95, 134.8, '国際'],
    [72, 90, 64, 139.3, '理数'],
    [72, 88, 82, 134.2, '普通'],
    [74, 93, 79, 158.3, '理数'],
    [75, 81, 81, 158.7, '普通'],
    [75, 82, 79, 155.1, '普通'],
    [75, 89, 71, 148.3, '普通'],
    [76, 94, 66, 133.8, '理数'],
    [76, 88, 55, 169.8, '理数'],
    [76, 78, 82, 148.9, '普通'],
    [76, 68, 93, 152.6, '国際'],
    [77, 77, 76, 160.8, '理数'],
    [77, 65, 91, 160.6, '国際'],
    [77, 73, 92, 147, '国際'],
    [77, 70, 91, 143.6, '国際'],
    [78, 82, 81, 161.5, '普通'],
    [78, 64, 92, 136.1, '国際'],
    [78, 74, 86, 164.8, '国際'],
    [78, 62, 92, 145.7, '国際'],
    [79, 85, 67, 161, '理数'],
    [79, 85, 65, 148.8, '理数'],
    [79, 71, 88, 157.1, '国際'],
    [80, 86, 77, 166, '普通'],
    [80, 82, 82, 173.7, '普通'],
    [80, 65, 92, 167.9, '国際'],
    [81, 87, 69, 164.1, '理数'],
    [81, 77, 98, 158.7, '国際'],
    [82, 85, 67, 150.9, '理数'],
    [82, 97, 65, 150.5, '理数'],
    [82, 78, 87, 166.8, '普通'],
    [82, 76, 76, 162.2, '普通'],
    [82, 82, 79, 136.7, '普通'],
    [83, 93, 71, 162.9, '理数'],
    [83, 73, 78, 159.7, '普通'],
    [83, 62, 92, 158.7, '国際'],
    [83, 81, 87, 154.3, '国際'],
    [83, 59, 92, 152.6, '国際'],
    [84, 84, 69, 133.6, '理数'],
    [84, 87, 79, 164, '普通'],
    [85, 76, 83, 159.3, '普通'],
    [85, 80, 82, 145.6, '普通'],
    [85, 83, 73, 152.9, '普通'],
    [85, 77, 85, 159.1, '国際'],
    [86, 80, 80, 164.8, '普通'],
    [87, 79, 75, 169.7, '普通'],
    [87, 62, 96, 162.1, '国際'],
    [87, 63, 91, 175.5, '国際'],
    [88, 90, 66, 176.3, '理数'],
    [89, 89, 75, 167.9, '理数'],
    [89, 86, 74, 156.5, '理数'],
    [89, 83, 76, 181.5, '普通'],
    [90, 87, 77, 163.9, '理数'],
    [90, 94, 65, 137.8, '理数'],
    [91, 73, 91, 173.7, '国際'],
    [91, 68, 91, 168.1, '国際'],
    [93, 68, 97, 159.1, '国際'],
    [98, 89, 96, 171.7, '普通'],
], columns=['国語', '数学', '英語', '身長', 'クラス'])
df

    国語  数学  英語     身長 クラス
0   67  88  72  164.2  理数
1   69  97  62  170.8  理数
2   70  84  72  143.9  理数
3   70  65  95  134.8  国際
4   72  90  64  139.3  理数
5   72  88  82  134.2  普通
6   74  93  79  158.3  理数
7   75  81  81  158.7  普通
8   75  82  79  155.1  普通
9   75  89  71  148.3  普通
10  76  94  66  133.8  理数
11  76  88  55  169.8  理数
12  76  78  82  148.9  普通
13  76  68  93  152.6  国際
14  77  77  76  160.8  理数
15  77  65  91  160.6  国際
16  77  73  92  147.0  国際
17  77  70  91  143.6  国際
18  78  82  81  161.5  普通
19  78  64  92  136.1  国際
20  78  74  86  164.8  国際
21  78  62  92  145.7  国際
22  79  85  67  161.0  理数
23  79  85  65  148.8  理数
24  79  71  88  157.1  国際
25  80  86  77  166.0  普通
26  80  82  82  173.7  普通
27  80  65  92  167.9  国際
28  81  87  69  164.1  理数
29  81  77  98  158.7  国際
30  82  85  67  150.9  理数
31  82  97  65  150.5  理数
32  82  78  87  166.8  普通
33  82  76  76  162.2  普通
34  82  82  79  136.7  普通
35  83  93  71  162.9  理数
36  83  73  78  159.7  普通
37  83  62  92  158.7  国際
38  83  81  87  154.3  国際
39  83  59  92  152.6  国際
40  84  84  69  133.6  理数
41  84  87  79  164.0  普通
42  85  76  83  159.3  普通
43  85  80  82  145.6  普通
44  85  83  73  152.9  普通
45  85  77  85  159.1  国際
46  86  80  80  164.8  普通
47  87  79  75  169.7  普通
48  87  62  96  162.1  国際
49  87  63  91  175.5  国際
50  88  90  66  176.3  理数
51  89  89  75  167.9  理数
52  89  86  74  156.5  理数
53  89  83  76  181.5  普通
54  90  87  77  163.9  理数
55  90  94  65  137.8  理数
56  91  73  91  173.7  国際
57  91  68  91  168.1  国際
58  93  68  97  159.1  国際
59  98  89  96  171.7  普通

### 無作為抽出
母集団から標本を偏りなく選ぶ方法の1つに，無作為抽出がある。無作為抽出では，母集団のどのデータも同じ確率で標本に選ばれる。

In [ ]:
# 無作為に20人を標本として抽出する
df_r = df.sample(n=20, random_state=0) #'df'から無作為に20行のデータを抽出
df_r

    国語  数学  英語     身長 クラス
26  80  82  82  173.7  普通
35  83  93  71  162.9  理数
59  98  89  96  171.7  普通
28  81  87  69  164.1  理数
11  76  88  55  169.8  理数
2   70  84  72  143.9  理数
34  82  82  79  136.7  普通
58  93  68  97  159.1  国際
40  84  84  69  133.6  理数
22  79  85  67  161.0  理数
4   72  90  64  139.3  理数
10  76  94  66  133.8  理数
30  82  85  67  150.9  理数
41  84  87  79  164.0  普通
33  82  76  76  162.2  普通
43  85  80  82  145.6  普通
49  87  63  91  175.5  国際
7   75  81  81  158.7  普通
14  77  77  76  160.8  理数
32  82  78  87  166.8  普通

無作為抽出した標本の平均値と，全数調査（母集団）の平均値を比べる。

In [ ]:
# 無作為抽出と全数調査の各テストの平均値を計算する
mean_r = df_r[['国語', '数学', '英語']].mean() #無作為抽出の平均値
mean_all = df[['国語', '数学', '英語']].mean() #全数調査の平均値

pd.DataFrame([mean_all, mean_r], index=['全数調査', '無作為抽出'])

              国語         数学         英語
全数調査   81.166667  79.566667  80.116667
無作為抽出  81.400000  82.650000  76.300000

### 標本抽出とバイアス

クラスの情報を用いて，理数科，または国際科に所属している学生のみを標本として抽出する。

In [ ]:
# 理数科の学生を標本として抽出する
df_s = df[df['クラス'] == '理数'] #'クラス'の列が'理数'のデータを抽出
df_s

    国語  数学  英語     身長 クラス
0   67  88  72  164.2  理数
1   69  97  62  170.8  理数
2   70  84  72  143.9  理数
4   72  90  64  139.3  理数
6   74  93  79  158.3  理数
10  76  94  66  133.8  理数
11  76  88  55  169.8  理数
14  77  77  76  160.8  理数
22  79  85  67  161.0  理数
23  79  85  65  148.8  理数
28  81  87  69  164.1  理数
30  82  85  67  150.9  理数
31  82  97  65  150.5  理数
35  83  93  71  162.9  理数
40  84  84  69  133.6  理数
50  88  90  66  176.3  理数
51  89  89  75  167.9  理数
52  89  86  74  156.5  理数
54  90  87  77  163.9  理数
55  90  94  65  137.8  理数

In [ ]:
# 国際科の学生を標本として抽出する
df_i = df[df['クラス'] == '国際'] #'クラス'の列が'国際'のデータを抽出
df_i

    国語  数学  英語     身長 クラス
3   70  65  95  134.8  国際
13  76  68  93  152.6  国際
15  77  65  91  160.6  国際
16  77  73  92  147.0  国際
17  77  70  91  143.6  国際
19  78  64  92  136.1  国際
20  78  74  86  164.8  国際
21  78  62  92  145.7  国際
24  79  71  88  157.1  国際
27  80  65  92  167.9  国際
29  81  77  98  158.7  国際
37  83  62  92  158.7  国際
38  83  81  87  154.3  国際
39  83  59  92  152.6  国際
45  85  77  85  159.1  国際
48  87  62  96  162.1  国際
49  87  63  91  175.5  国際
56  91  73  91  173.7  国際
57  91  68  91  168.1  国際
58  93  68  97  159.1  国際

In [ ]:
# 理数科・国際科の学生の各テストの平均値を計算し，無作為抽出・全数調査の結果と比較する
mean_s = df_s[['国語', '数学', '英語']].mean() #理数科の平均値
mean_i = df_i[['国語', '数学', '英語']].mean() #国際科の平均値

pd.DataFrame([mean_all, mean_r, mean_s, mean_i], index=['全数調査', '無作為抽出', '理数科', '国際科'])

              国語         数学         英語
全数調査   81.166667  79.566667  80.116667
無作為抽出  81.400000  82.650000  76.300000
理数科    79.850000  88.650000  68.800000
国際科    81.700000  68.350000  91.600000